# Runs INSIDE Windows Sandbox only. Creates a temporary guest-local standard
# user, then invokes the same acceptance driver used by CI under that account.
[CmdletBinding()]
param([Parameter(Mandatory = $true)][string]$ReportDir)
$ErrorActionPreference = 'Stop'
$sourceRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$guestRoot = 'C:\Users\Public\Anki Test ' + [char]0x00e4
$userName = 'ACFStandardTest'
if ($env:USERNAME -ne 'WDAGUtilityAccount') {
    throw 'This harness is restricted to the disposable Windows Sandbox guest.'
}
if ([IO.Path]::GetFullPath($ReportDir).TrimEnd('\') -ne 'C:\ACF-Reports') {
    throw 'Use the dedicated C:\ACF-Reports mapping generated by prepare_windows_sandbox.ps1.'
}
$guestReports = $null
$process = $null

function Copy-ReportTree([string]$source, [string]$destination) {
    # Never follow a guest-created junction/symlink while collecting artifacts.
    $item = Get-Item -LiteralPath $source -Force
    if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) { return }
    if (Test-Path -LiteralPath $destination) {
        $destinationItem = Get-Item -LiteralPath $destination -Force
        if ($destinationItem.Attributes -band [IO.FileAttributes]::ReparsePoint) {
            throw 'Report destination contains an unexpected junction or symlink.'
        }
    }
    if ($item.PSIsContainer) {
        New-Item -ItemType Directory -Path $destination -Force | Out-Null
        Get-ChildItem -LiteralPath $source -Force | ForEach-Object {
            Copy-ReportTree $_.FullName (Join-Path $destination $_.Name)
        }
    } else {
        Copy-Item -LiteralPath $source -Destination $destination -Force
    }
}

function Confirm-AcceptanceCompletion([string]$Directory, [string]$ExpectedNonce, [int]$ExpectedProcessId) {
    $completionPath = Join-Path $Directory 'driver-complete.json'
    $resultPath = Join-Path $Directory 'result.json'
    if (-not (Test-Path -LiteralPath $completionPath) -or -not (Test-Path -LiteralPath $resultPath)) {
        throw 'Standard-user acceptance ended without complete result evidence. Inspect the captured logs.'
    }
    $completion = Get-Content -LiteralPath $completionPath -Raw | ConvertFrom-Json
    $result = Get-Content -LiteralPath $resultPath -Raw | ConvertFrom-Json
    if ($completion.completed -ne $true -or $completion.nonce -ne $ExpectedNonce -or
        $completion.process_id -ne $ExpectedProcessId -or $null -eq $completion.exit_code -or
        $completion.exit_code -ne $result.exit_code -or $completion.success -ne $result.success) {
        throw 'Standard-user acceptance completion does not match this process and its result.'
    }
    if ($completion.exit_code -ne 0 -or $result.success -ne $true) {
        throw "Standard-user acceptance failed (exit $($completion.exit_code)): $($result.error)"
    }
}

try {
    $secret = ConvertTo-SecureString ('ACF!' + [guid]::NewGuid().ToString('N') + 'a1') -AsPlainText -Force
    $user = New-LocalUser -Name $userName -Password $secret -AccountNeverExpires -PasswordNeverExpires
    $usersGroup = Get-LocalGroup -SID 'S-1-5-32-545'
    Add-LocalGroupMember -Group $usersGroup -Member $user
    New-Item -ItemType Directory -Path $guestRoot -Force | Out-Null
    Get-ChildItem -LiteralPath $sourceRoot -Force | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination $guestRoot -Recurse
    }
    & icacls.exe $guestRoot /grant ('*' + $user.SID.Value + ':(OI)(CI)M') /T /Q | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'Could not grant the guest user access to its workspace.' }
    # Keep standard-user reports inside the guest. The harness copies them to
    # the narrow host report share after the test process exits.
    $guestReports = Join-Path $guestRoot 'decks\_windows-reports_rebuild'
    $credential = [Management.Automation.PSCredential]::new("$env:COMPUTERNAME\$userName", $secret)
    $completionNonce = [guid]::NewGuid().ToString('N')
    $arguments = '-NoProfile -ExecutionPolicy Bypass -File "' +
        (Join-Path $guestRoot 'tests\integration\windows_acceptance.ps1') +
        '" -ReportDir "' + $guestReports + '" -RequireNonAdmin -NetworkIsolationHandshake -CompletionNonce ' + $completionNonce
    $process = Start-Process -FilePath "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" `
        -ArgumentList $arguments -Credential $credential -LoadUserProfile -WindowStyle Hidden -PassThru
    # Retain the original process handle while it is alive. Some PowerShell 5
    # Start-Process/Credential combinations still return a null ExitCode later,
    # so a process-bound completion record remains the required evidence.
    $retainedProcessHandle = $process.Handle
    $networkDisabled = $false
    $deadline = [DateTime]::UtcNow.AddMinutes(45)
    while (-not $process.HasExited) {
        if ([DateTime]::UtcNow -gt $deadline) { throw 'Standard-user acceptance exceeded 45 minutes.' }
        $requestPath = Join-Path $guestReports 'request-network-offline.json'
        if (-not $networkDisabled -and (Test-Path -LiteralPath $requestPath)) {
            $request = Get-Content -LiteralPath $requestPath -Raw | ConvertFrom-Json
            $adapters = @(Get-NetAdapter | Where-Object Status -eq 'Up')
            if (-not $adapters) { throw 'No guest network adapter available for isolation proof.' }
            $adapters | Disable-NetAdapter -Confirm:$false
            if (Get-NetAdapter | Where-Object Status -eq 'Up') { throw 'A guest network adapter remains enabled.' }
            $responseTemp = Join-Path $guestReports 'network-isolated.json.tmp'
            @{ nonce = $request.nonce; network_isolated = $true; adapters = @($adapters.Name) } |
                ConvertTo-Json -Depth 3 |
                Set-Content -LiteralPath $responseTemp -Encoding UTF8
            Move-Item -LiteralPath $responseTemp -Destination (Join-Path $guestReports 'network-isolated.json')
            $networkDisabled = $true
        }
        Start-Sleep -Seconds 1
        $process.Refresh()
    }
    $process.WaitForExit()
    Confirm-AcceptanceCompletion $guestReports $completionNonce $process.Id
    if (-not $networkDisabled) { throw 'The acceptance process never completed guest network isolation.' }
    if ($null -ne $process.ExitCode -and $process.ExitCode -ne 0) {
        throw "Standard-user process exited unexpectedly: $($process.ExitCode)"
    }
}
catch {
    $failure = $_
    if ($process -and -not $process.HasExited) {
        # This exact child and its descendants exist only inside the disposable guest.
        & "$env:SystemRoot\System32\taskkill.exe" /PID $process.Id /T /F | Out-Null
    }
    New-Item -ItemType Directory -Path $ReportDir -Force | Out-Null
    $failure | Out-String | Set-Content -LiteralPath (Join-Path $ReportDir 'sandbox-error.txt') -Encoding UTF8
    throw
}
finally {
    # Retain partial evidence even if the coordinator fails before setup finishes.
    if ($guestReports -and (Test-Path -LiteralPath $guestReports)) {
        $reportItem = Get-Item -LiteralPath $guestReports -Force
        if (-not ($reportItem.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
            $allowed = @('acceptance.log', 'cold-setup.log', 'offline-setup.log', 'unit-tests.log',
                'provenance.log', 'driver-error.txt', 'driver-complete.json', 'runtime-logs',
                'before.json', 'provenance.json', 'doctor.json',
                'setup-state.json', 'result.json', 'request-network-offline.json',
                'network-isolated.json', 'decks', 'extracted')
            Get-ChildItem -LiteralPath $guestReports -Force |
                Where-Object { $_.Name -in $allowed } | ForEach-Object {
                    Copy-ReportTree $_.FullName (Join-Path $ReportDir $_.Name)
                }
        }
    }
}
